### PR TITLE
Update the footer to say 2016

### PR DESCRIPTION
**Pull request by wadeanthony0100**
@vuzDylan wam9729 membership pls

### CODE REVIEW

**Comment by kristenmills** [comment]
If you address #53, I'll convince Dylan to give you 2 memberships.

**Comment by wadeanthony0100** [comment]
This should work until the year 3000.

**Comment by wadeanthony0100** [comment]
Because I don't know what I'm doing. Gimme a second...

**Comment by kristenmills** [comment]
:+1:

**Comment by wadeanthony0100** [comment]
That should be better

**Comment by wadeanthony0100** [comment]
@vuzDylan 2 memberships pls wam9729

**Pull request merged**
